blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.show_posts, name='blog_home' ),
]

cars/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('blog/', include('blog.urls')),
]

main/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index' ),
    path('person/<int:person_id>', views.person_view, name='person' ),
    path('add_vehicle', views.add_vehicle, name='add_vehicle'),
    path('add_passenger', views.add_person_to_car, name='add_passenger'),
    path('add_vehicle_new', views.add_vehicle_modelform, name='add_vehicle_new'),
    path('update_vehicle/<int:vehicle_id>', views.update_vehicle, name='update_vehicle'),
    path('update_color', views.set_color, name='update_color'),
]

blog/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from main.models import Person
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        return f'Category: {self.name}'


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Person, on_delete=models.CASCADE)
    categories = models.ManyToManyField(Category, blank=True)


class Comment(models.Model):
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Person, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

main/models.py
from django.db import models

# Create your models here.
class Person(models.Model):
    first_name = models.CharField(max_length=80)
    last_name = models.CharField(max_length=80)
 
    
    def __str__(self):
        return f'{self.first_name} {self.last_name}'
    
class ImageProfile (models.Model):
    person = models.OneToOneField(Person, on_delete=models.CASCADE)
    image = models.URLField()

    def __str__(self):
        return f'ImageProfile of {self.person}'

class Vehicle(models.Model):
    manufacturer = models.CharField(max_length=80)
    model_name = models.CharField(max_length=80)
    color = models.CharField(max_length=80)
    milage = models.IntegerField()
    top_speed = models.IntegerField(default=50)
    owner = models.ForeignKey(Person, on_delete=models.PROTECT)
    passengers = models.ManyToManyField(Person, related_name='in_cars')

    def __str__(self):
        return f'{self.manufacturer} {self.model_name}'

    def get_rentalrate(self):
        return self.size.rentalrate_set.filter(type=self.type).first()

main/forms.py
from django import forms
from .models import Person, Vehicle

def validate_name(name):
    # check if they are numbers in the name
    if not name.isalpha():
        print("Invalid name")  
        raise forms.ValidationError(f'The name {name} is invalid, it contains non-alphabetic characters')



class VehicleForm(forms.Form):
    manufacturer = forms.CharField(
        min_length=5,
        max_length=80, 
        label='Made By', 
        help_text='this is the manufacturer of the car, min 54 chars max 80', 
        error_messages= 
            {
                'required':'hello hacker', 
                'max_length':'youve exceeded the allowed char limit'
                },
        widget= forms.TextInput(attrs={'placeholder':'Kia'}),
        validators=[validate_name]
        )
    model_name = forms.CharField(max_length=80)
    color = forms.CharField(max_length=80, validators=[validate_name])
    milage = forms.IntegerField()
    owner = forms.ModelChoiceField(queryset=Person.objects.all())
    field_order = ['owner','manufacturer','model_name', 'milage', 'color' ]


class SelectPassenger(forms.Form):
    passenger = forms.ModelChoiceField(queryset=Person.objects.all())
    vehicle = forms.ModelChoiceField(queryset=Vehicle.objects.exclude(model_name='world'))

class NewVehicleForm(forms.ModelForm):
    class Meta:
        model = Vehicle
        exclude = ['passengers', 'top_speed', 'owner']

class SetVehiclesColor(forms.Form):
    vehicles = forms.ModelMultipleChoiceField(queryset=Vehicle.objects.all())
    color = forms.CharField()

blog/views.py
from django.shortcuts import render
from .models import Post

# Create your views here.

def show_posts(request):
    posts = Post.objects.all()
    return render(request, 'blog/posts.html', {'posts': posts})

main/views.py
from .models import Vehicle, Person
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from .forms import VehicleForm, SetVehiclesColor, SelectPassenger, NewVehicleForm
import random
# Create your views here.

def index(request):
    # cars = get_list_or_404(Vehicle, color='red')
    cars = Vehicle.objects.all()
    return render(request, 'main/index.html', {'cars':cars})

def person_view(request,person_id):

    # p = Person.objects.get(id=person_id)
    p = get_object_or_404(Person, id=person_id)

    return render(request, 'main/person.html', {'person':p})
    
def add_vehicle(request):
    cars = Vehicle.objects.all()
    if request.method == 'GET':
        form = VehicleForm()
        
    elif request.method == 'POST':
        form = VehicleForm(request.POST)
        print(form.data)

        if form.is_valid():
            print(form.cleaned_data)
            Vehicle.objects.create(**form.cleaned_data) 

            # return redirect('index')
    return render(request, 'main/add_vehicle.html', {'form':form, 'cars':cars})

def add_vehicle_modelform(request):
    cars = Vehicle.objects.all()
    if request.method == 'GET':
        form = NewVehicleForm()
    if request.method == 'POST':
        form = NewVehicleForm(request.POST)
        if form.is_valid():
            vehicle = form.save(commit=False)
            vehicle.owner = random.choice(Person.objects.all())
            vehicle.save()
    return render(request, 'main/add_vehicle.html', {'form':form, 'cars':cars})

def update_vehicle(request, vehicle_id):
    vehicle = get_object_or_404(Vehicle, id=vehicle_id)
    if request.method == 'GET':
        form = NewVehicleForm(instance=vehicle)
    if request.method == 'POST':
        form = NewVehicleForm(request.POST, instance=vehicle)
        if form.is_valid():
            form.save()
    return render(request, 'main/add_vehicle.html', {'form':form})

def add_person_to_car(request):
    if request.method == "GET":
        form = SelectPassenger()
    elif request.method == 'POST':
        form = SelectPassenger(request.POST)
        if form.is_valid():
            person = form.cleaned_data['passenger']
            vehicle = form.cleaned_data['vehicle']
            vehicle.passengers.add(person)
            return redirect('person', person.id)
    return render(request, 'main/add_person_to_vehicle.html', {'form':form})

def set_color(request):
    if request.method == "GET":
        form = SetVehiclesColor()
    elif request.method == 'POST':
        form = SetVehiclesColor(request.POST)
        if form.is_valid():
            color = form.cleaned_data['color']
            vehicles = form.cleaned_data['vehicles']
            print(vehicles)
            vehicles.update(color=color)
    return render(request, 'main/add_person_to_vehicle.html', {'form':form})

blog/templates/blog/posts.html
{% extends 'base.html' %}
{% block title %}
Blog Home
{% endblock %}

{%block content%}
<div class='row'>
{% for post in posts%}
<div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">{{post.title}}</h5>
      <h6 class="card-subtitle mb-2 text-muted">{{post.timestamp|timesince}}</h6>
      <p class="card-text">{{post.content}}</p>
    
    </div>
  </div>
{% endfor %}
</div>
{% endblock %}

main/templates/add_vehicle.html
{% extends 'base.html'%}

{% block content %}
<form method='post'>
    {% csrf_token %}
    {{form.as_p}}
<button type="submit">Save</button>
</form>
{% endblock %}

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Garage - {% block title%} {% endblock%}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">    
    {% block style%}

    {% endblock %}
</head>
<body>
{% block content %}

{% endblock %}

</body>
</html>

main/templates/index.html
{% extends 'base.html'%}
{% load static %}
{% block style%}
<link rel='stylesheet' href='{% static "css/index.css" %}'>

{% endblock %}
{% block content%}
<h4>all cars</h4>
    {% for car in cars %}
        <h4>{{car.manufacturer}} {{car.model_name}}</h4>
        <ul>
            <li>Speed: {{car.top_speed}}</li>
            <li>Milage: {{car.milage}}</li>
            <li>Color: {{car.color}}</li>
            <li>Owner: <a href="{% url 'person' car.owner.id%}">{{car.owner.first_name}}</a></li>
        </ul>
    {% endfor %}

{% endblock %}

main/templates/main/add_person_to_vehicle.html
{% extends 'base.html'%}

{% block title%}
add passenger
{% endblock%}

{% block content %}
<form method='post'>
    {% csrf_token %}
    {{form.as_p}}
<button class='btn btn-success' type="submit">Save</button>
</form>

{% endblock %}

main/templates/main/add_vehicle.html
{% extends 'base.html'%}
{% block title%}
Intake New
{% endblock%}
{% block content %}
<form method='post'>
    {% csrf_token %}
    {{form.as_p}}
<button class='btn btn-success' type="submit">Save</button>
</form>
<hr>
{% for car in cars %}
        <h4>{{car.manufacturer}} {{car.model_name}}</h4>
        <ul>
            <li>Speed: {{car.top_speed}}</li>
            <li>Milage: {{car.milage}}</li>
            <li>Color: {{car.color}}</li>
            <li>Owner: <a class="btn btn-primary" href="{% url 'person' car.owner.id%}">{{car.owner.first_name}}</a></li>
        </ul>
    {% endfor %}
{% endblock %}

main/templates/main/index.html
{% extends 'base.html'%}
{% load static %}
{% block style%}
<link rel='stylesheet' href='{% static "css/index.css" %}'>

{% endblock %}
{% block content%}
<h4>all cars</h4>
    {% for car in cars %}
        <h4>{{car.manufacturer}} {{car.model_name}}</h4>
        <ul>
            <li>Speed: {{car.top_speed}}</li>
            <li>Milage: {{car.milage}}</li>
            <li>Color: {{car.color}}</li>
            <li>Owner: <a href="{% url 'person' car.owner.id%}">{{car.owner.first_name}}</a></li>
            
        </ul>
        <hr>
        <h5>passengers</h5>
        <ul>
            {% for person in car.passengers.all %}
                <li>{{person}}</li>
            {% endfor %}
        </ul>
    {% endfor %}

{% endblock %}

main/templates/main/person.html
{% extends 'base.html'%}
{% load static %}

{% block content%}
<a href="{% url 'index' %}">back to homepage</a>
<h4>Name: {{person.first_name}} {{person.last_name}}</h4>
<ul>
{% for vehicle in person.vehicle_set.all %}
    <li>{{vehicle.manufacturer}} {{vehicle.model_name}}</li>
{% endfor %}
</ul>
{% endblock %}